# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: davidburguete
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mirandaapi
service: MirandaAPI
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "public/**"
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs22.x
functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true